### ISSUE TITLE
3.1.5 fails angular (typescript) build

### ISSUE THREAD

**Issue by inbarshani** [Vibrant-Colors/node-vibrant#111]
ERROR in node_modules/node-vibrant/lib/color.d.ts(19,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/node-vibrant/lib/color.d.ts(20,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/node-vibrant/lib/color.d.ts(21,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/node-vibrant/lib/color.d.ts(22,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/node-vibrant/lib/color.d.ts(23,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/node-vibrant/lib/color.d.ts(24,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/node-vibrant/lib/color.d.ts(25,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/node-vibrant/lib/color.d.ts(37,9): error TS1086: An accessor cannot be declared in an ambient context.
node_modules/node-vibrant/lib/color.d.ts(38,9): error TS1086: An accessor cannot be declared in an ambient context.

**Comment by ameerahallie** [comment]
I am also getting this error on trying to run a prod build.

**Comment by Feargalicious** [comment]
I think this is due to angular cli not being compatible with ts 3.7, until they update it you'll have to use ts <=3.5.3, so I had to roll back to 3.1.4

**Comment by crutchcorn** [comment]
Is this the case with Angular 9, does anyone know? I know they support TS3.7 now

**Comment by princemaple** [comment]
hey I just discovered this nice lib. I haven't used it in a project, but if it's true that the bug is related to typescript version it should be resolved now. I've been compiling angular 9 project with typescript 3.8 for a few weeks.

**Comment by crutchcorn** [comment]
I'm going to close this. `3.1.5` is older, and, upon spinning up a new project in Angular with the newest TypeScript, it seems that `3.1.6` has fixed this

Please let me know if I'm mistaken
