### ISSUE TITLE
(Browser) Importing Vibrant gives TypeError: second argument to Function.prototype.apply must be an array

### ISSUE THREAD

**Issue by thefyrewire** [Vibrant-Colors/node-vibrant#121]
Hello, I tried to import Vibrant with:

```js
import * as Vibrant from 'node-vibrant'
```
...and received this error in Firefox 86.0 (64-bit):

![image](https://user-images.githubusercontent.com/8237302/109814135-0a662580-7c26-11eb-880b-a9ab7a20b7ff.png)

However, seems to be fine on Chrome 88.0.4324.190.

I cloned the repo and ran `npm run build` myself, then used the new `dist` and `lib` folders, and the error has now gone away. Hopefully this helps anyone else having similar problems, not sure if maybe a gremlin jumped into the build process.

**Comment by JackLot** [comment]
+1 same exact behavior

**Comment by malinda666** [comment]
using, 
`import Vibrant from "node-vibrant/dist/vibrant";`  solved the problem for me. in a React based project

**Comment by crutchcorn** [comment]
This is the same issue as this: #85, which I'm working on fixing right now

Temporary solution is to downgrade to `3.1.6` or use the import @malinda666 suggested. The `alpha` release was never intended on being made stable and was an accident
