### ISSUE TITLE
Different result in Firefox and Chrome with same image

### ISSUE THREAD

**Issue by Fauphi** [Vibrant-Colors/node-vibrant#122]
I'm getting different palette results for the same image in Firefox and Chrome.
Is there a solution for this or are the results dependent on the browsers canvas implementation?

**Image:** 

[https://ibb.co/gVjQ9c8](https://ibb.co/gVjQ9c8)

**Chrome:**

"Vibrant", hex: "#c86886", population: 7
"LightVibrant", hex: "#da859c", population: 5
"DarkVibrant", hex: "#612336", population: 0
"Muted", hex: "#70283f", population: 0
"DarkMuted", hex: "#70283f", population: 0
"LightMuted", hex: "#752339", population: 0

**Firefox:**

"Vibrant", hex: "#bc5474"​​, population: 3
"LightVibrant", hex: "#f09cb4"​​, population: 2
"Muted", hex: "#ac4c64"​​, population: 1
"DarkVibrant", hex: "#5f2537"​​, population: 0
"DarkMuted", hex: "#6d2b3f"​​, population: 0
"LightMuted", hex: "#841434"​​, population: 0

**vibrant version:** 

3.1.5 and 3.2.1

Thanks!

**Comment by danbulant** [comment]
[Browser inconsistencies, see readme](https://github.com/Vibrant-Colors/node-vibrant#result-consistency)

**Comment by dukhevych** [comment]
Sometimes inconsistencies are quite huge. Is there a way to play with some settings to make it work as crossbrowser as possible?

**Comment by crutchcorn** [comment]
AFAIK there's little/nothing we can do about this inconsistency. If anyone has any ideas, please open a new issue with the details inlined
