### ISSUE TITLE
How to call the util function rgbToHex? Or How to get pallete in Hex format?

### ISSUE THREAD

**Issue by guloic** [Vibrant-Colors/node-vibrant#125]
The Readme mentions `rgbToHex` but the code does not export that function in the util.ts. Any idea how that can be used?

If `getPallete` or `getSwatches` can return hex directly along with population count, that would be great.

**Comment by chuckdries** [comment]
It's on the swatch object. For example, with getPallete, you might call
```js
const vibrantData = await Vibrant.from(filePath)
  .quality(1)
  .getPalette();

const vibrantHex = vibrantData.Vibrant.getHex()
```
