### ISSUE TITLE
Pallete is much different from the source image

### ISSUE THREAD

**Issue by guloic** [Vibrant-Colors/node-vibrant#126]
**Issue** : Palette colors don't match source image
**Expected** : Palette colors should match source image
**Actual** : Palette colors are different from source image

**Steps to reproduce**
I used this source image to generate a palette.
![Source Image](https://en.seedfinder.eu/pics/00breeder/707seedbank.jpg)

And I got this palette -
```json
{
  "Vibrant": {
    "rgb": [
      132,
      200,
      68
    ],
    "population": 2
  },
  "DarkVibrant": {
    "rgb": [
      10,
      142,
      70
    ],
    "population": 65
  },
  "LightVibrant": {
    "rgb": [
      166,
      230,
      118
    ],
    "population": 12
  },
  "Muted": {
    "rgb": [
      138,
      168,
      104
    ],
    "population": 67
  },
  "DarkMuted": {
    "rgb": [
      75,
      82,
      50
    ],
    "population": 230
  },
  "LightMuted": {
    "rgb": [
      204,
      212,
      164
    ],
    "population": 1
  }
}
```

The palette doesn't change irrespective of `quality` value or `colorCount` value. And if you see the color with highest population color ("DarkMuted"), the color is not even part of the image.

How to tweak this behaviour? I need more accurate palette.

**Comment by crutchcorn** [comment]
This seems to work fairly well for me on Chrome latest:

![image](https://github.com/user-attachments/assets/3840a4d7-eaf9-4a7b-b339-83429762c682)
