### ISSUE TITLE
Causes react-refresh to crash

### ISSUE THREAD

**Issue by BasixKOR** [Vibrant-Colors/node-vibrant#128]
I'm not really sure who to report this bug, so I'm gonna be writing issue for both React and this.

Reproduction of the bug: https://codesandbox.io/s/vibrant-react-repro-bx3t9

It seems like just even importing node-vibrant breaks react-refresh for some reason.

**Comment by crutchcorn** [comment]
This is the same issue as this: #85, which I'm working on fixing right now

Temporary solution is to downgrade to `3.1.6`. The `alpha` release was never intended on being made stable and was an accident
