### ISSUE TITLE
Using ES6 get an error

### ISSUE THREAD

**Issue by bitdom8** [Vibrant-Colors/node-vibrant#129]
Thanks for great repo. Get an error though: TypeError: this.WorkerClass is not a constructor

```
	import Vibrant from 'node-vibrant'
	var img = document.createElement('img');
img.setAttribute('src', '/favicon.png')

img.addEventListener('load', function() {
    var vibrant = new Vibrant(img);
    var swatches = vibrant.swatches()
    for (var swatch in swatches)
        if (swatches.hasOwnProperty(swatch) && swatches[swatch])
            console.log(swatch, swatches[swatch].getHex())

    /*
     * Results into:
     * Vibrant #7a4426
     * Muted #7b9eae
     * DarkVibrant #348945
     * DarkMuted #141414
     * LightVibrant #f3ccb4
     */
});
```

**Comment by bitdom8** [comment]
Thanks to the another thread. Error is gone. However when I run 

"pnpm run build"

and 

pnpm run preview

The error is resolved however when I build sveltekit it appears

Uncaught TypeError: Cannot read property 'filters' of undefined``

**Comment by crutchcorn** [comment]
This is the same issue as this: #85, which I'm working on fixing right now

Temporary solution is to downgrade to `3.1.6`. The `alpha` release was never intended on being made stable and was an accident

Please open a new issue for the `filters` bug
