### ISSUE TITLE
Different results on desktop vs mobile browser for same image

### ISSUE THREAD

**Issue by nandorojo** [Vibrant-Colors/node-vibrant#132]
# Bug

Mobile browsers and desktop browsers return a different set of colors for the same image.

Take this image:

<img src="https://user-images.githubusercontent.com/13172299/161787136-40aaff27-3984-4219-b8a7-609b4ac19bb1.png" width="300" />

The colors it produces are radically different on a mobile and desktop browser.

To see this in action, [open this URL](https://5rr127.csb.app/) on both a mobile and desktop browser.

## Steps To Reproduce

1. Use this image URL: https://res.cloudinary.com/dn29xlaeh/image/upload/q_75,w_640/v1/beatgig-live/quhilykqgarpqnf9peyk
2. Get the colors on a mobile browser
3. Get the colors on a desktop browser

Describe what you expected to happen:

1. The colors on both platforms should be the same.

## Reproducible sample code

Here is a [minimal CodeSandbox reproduction](https://codesandbox.io/s/elated-hugle-5rr127?file=/src/App.js:0-951). I made it as simple as possible.

These are the colors it comes up with on a desktop browser:

<img width="1698" alt="image" src="https://user-images.githubusercontent.com/13172299/161798901-e2296c6f-a694-41dc-b3e0-11f3cc890066.png">

Meanwhile, here it is on a mobile browser (you can open the sandbox [preview URL](https://5rr127.csb.app/) to view it there.)

![React App](https://user-images.githubusercontent.com/13172299/161799299-ec65b7b8-33eb-47cf-ad66-2f960afe948c.jpeg)

**Comment by crutchcorn** [comment]
AFAIK there's little/nothing we can do about this inconsistency. If anyone has any ideas, please open a new issue with the details inlined
