### ISSUE TITLE
get more than 6 colors

### ISSUE THREAD

**Issue by danarosca** [Vibrant-Colors/node-vibrant#134]
hi guys, is there a way to get more than 6 colours in the end? Maybe a way to have access to the initial palette? Thanks

**Comment by crutchcorn** [comment]
You can get as many colors as you'd like via:

```typescript
const vibrant = Vibrant.from(img).maxColorCount(12).build()
vibrant.getPalettes().then(() => console.log(vibrant.result.colors))
```

Just keep in mind that this is the `maxColorCount`, not an exact color count. You may request 12 colors and get 9.

These colors are also not named in any way for better readability.
