### ISSUE TITLE
Security vulnerability on a dependency 'jpeg-js'

### ISSUE THREAD

**Issue by Sandakan** [Vibrant-Colors/node-vibrant#135]
A new security vulnerability "Infinite loop in jpeg-js" with high-level severity in one of the package's dependencies has been detected. Most probably, every version of node-vibrant could be affected.

**Comment by confuser** [comment]
Work around if on npm v8.3.0+ using [overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json/#overrides)

```
"overrides": {
    "node-vibrant": {
      "@vibrant/image-node": {
        "@jimp/types": {
          "@jimp/jpeg": {
            "jpeg-js": "^0.4.4"
          }
        }
      }
    }
  }
```

**Comment by Sandakan** [comment]
@confuser Thanks for the help. It fixed the vulnerability. 😁😁
