### ISSUE TITLE
Non-Integer values in swatch rgb results

### ISSUE THREAD

**Issue by fairbairn** [Vibrant-Colors/node-vibrant#140]
In certain scenarios, the swatch returned from getVibrant() can return an RGB tuplet that contains non-integer values, which don't convert to hex syntax and can cause issues.

It's an expected result, as RGB values should range from 0-255.

**Comment by crutchcorn** [comment]
I need a minimal reproduction to handle edgecases. Feel free to reopen the issue if you have them
