### ISSUE TITLE
Need help in fixing the Security Vulnerability when we use node-vibrant latest version (3.2.1-alpha & 3.1.6)

### ISSUE THREAD

**Issue by lo50g3usuresh** [Vibrant-Colors/node-vibrant#141]
Hi,

We have one high security vulnerability issue when using the node-vibrant package. We tried latest version 3.2.1-alpha and 3.1.6. 

Issue: file-type Denial of Service (DoS)
Introduced through
node-vibrant@3.1.6
Fixed in
file-type@16.5.4, @17.1.3.

Any timely help is highly appreciated.

Thanks,
Suresh

**Comment by lo50g3usuresh** [comment]
Please let me know if there are any progress on this.

**Comment by linkb15** [comment]
Found one on this library through Snyk as well with the library of xml2js

https://snyk.io/vuln/SNYK-JS-XML2JS-5414874?utm_source=slack

**Comment by crutchcorn** [comment]
This should be solved in `node-vibrant@4.0.0-alpha.5`
