### ISSUE TITLE
[Vulnerability] Update @jimp/custom to version 0.22.12

### ISSUE THREAD

**Issue by TarasIrisCRM** [Vibrant-Colors/node-vibrant#146]
node-vibrant@3.1.6 has vulnerability https://github.com/advisories/GHSA-x565-32qp-m3vf
Bumping @jimp/custom package to 0.22.12 seems will resolve this issue.
react-palette uses "node-vibrant": "^3.1.3" and node-vibrant@3.1.6 is the last stable version =(

**Comment by crutchcorn** [comment]
Should be fixed in `node-vibrant@4.0.0-alpha.5`
