### ISSUE TITLE
Proper project page

### ISSUE THREAD

**Issue by akfish** [Vibrant-Colors/node-vibrant#15]
Although this port is focused on node.js, it's time for a proper project page.
- [ ] Show cases
- [ ] Live demo
- [ ] Docs

**Comment by gmemstr** [comment]
I could take this on if it's still needed, loving using the library so far.

**Comment by akfish** [comment]
@gmemstr Thanks for the offer and I'm glad that you are enjoying using this lib. It means a lot. :)
I'm now in the process of making the project site (finally!). It should come online along with some new features/improvements in the next version.

**Comment by crutchcorn** [comment]
I've held off on making a project page as it was mentioned that @akfish was working on it. However, I already have a fair amount of code in doing so from writing: https://colorize.ceoss.io/

Is this still something being worked on or is there a want/need for a PR adding it in?

**Comment by crutchcorn** [comment]
Worth mentioning that we're defering working on the project page until we fix up some bugs and get the `develop` branch monorepo restructure documented properly.

**Comment by crutchcorn** [comment]
This page does not yet include docs, but we do have a demo now:

https://vibrant-colors.github.io/

Docs will come as future work to auto-generate our docs, provide official docs, and more
