### ISSUE TITLE
Color delta based clustering algorithm for quantization

### ISSUE THREAD

**Issue by akfish** [Vibrant-Colors/node-vibrant#58]
The MMCQ quantizer is not suitable for this kinda of applications. It does not reflect how human eyes percept colors. The generated colors are often unnatural. And most color information is simply lost.

I'm investigating a new approach to quantize the color, which uses color delta as distance function for clustering. Early experiments showed promising results.

**Comment by polarathene** [comment]
Did anything come from this?

**Comment by crutchcorn** [comment]
Sadly, this issue may be lost to time. I don't know what @akfish had in mind or how to achieve similar. PRs or ideas welcomed here. Closing for now
