### ISSUE TITLE
Allow an HTMLCanvasElement as source for the image

### ISSUE THREAD

**Issue by StephanBijzitter** [Vibrant-Colors/node-vibrant#75]
I already have a canvas and currently convert it into a base64 png, give it to vibrant and it then draws it on a canvas once more. This seems a bit redundant.

**Comment by maxcr** [comment]
Canvas operations are cheap since they are done on the GPU and not CPU. If your demographic is mainly really old android and IE then I guess you could rewrite it to merge the two canvas operations somehow but if were talking amount of milliseconds decreased on compute time it would be a negligible performance gain for anything made after 2012.

**Comment by StephanBijzitter** [comment]
>If your demographic is mainly really old android and IE 

Nail. Head. 😅

**Comment by maxcr** [comment]
I mean it seems that the WebAssembly implementation would solve the issue as that is the most possible performant state. Is the browser versions supported too old for WASM? If that's the case, it's going to take a lot of work.

**Comment by StephanBijzitter** [comment]
The only browser we have to support that doesn't support WASM is IE11 (sadly that's still a large minority of our users). I'll see if I can find some time to work on HTMLCanvasElement as input, but it could take a few months 😅

**Comment by maxcr** [comment]
I'll see about cooking up a patch for you buddy. Do you mind hosting your code somewhere for me so I can see how you're doing everything?

**Comment by PeterL1n** [comment]
I also wish this functionality is implemented. To convert an image to dataURL then convert back to canvas is not optimal

**Comment by StephanBijzitter** [comment]
Apologies for the late response, there's not really a way for me to host a sample repo as the codebase is a tad old and has a lot of external dependencies.

However in the end it's just a `<canvas>` element being painted on using FabricJS. They've got a lot of demos, perhaps those can be used instead? http://fabricjs.com/demos/

**Comment by crutchcorn** [comment]
Thi sseems like a logical feature request to me. @maxcr, has there been any work done by you on this subject matter? We'd love pull requests and I could help out with anything you might have. We're currently moving new development towards the `develop` monorepo structure, but if you already have code written for `master`, I can migrate that code manually like we did for #82

**Comment by crutchcorn** [comment]
Sorry y'all, but I'm closing this issue as it would add overhead to us and IE11 is no longer supported by even Microsoft
